version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rendevumvar-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - rendevumvar-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Password123" -Q "SELECT 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rendevumvar-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RendevumVar;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - rendevumvar-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rendevumvar-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - rendevumvar-network

networks:
  rendevumvar-network:
    driver: bridge

volumes:
  sqlserver-data:
